### PR TITLE
Fixed issues founded during testing of the game

### PR DESCRIPTION
**Pull request by RicsiToth**

### CODE REVIEW

**Comment by crnkjck** [comment]
The smaller issues to fix:

- [ ] Instead of “Pre ktorý prvok z domény predpokladáš, že formula ∃x (ma(John, x) ∧ (macka(x) ∨ pes(x))) je pravdivá ?” show “Pre ktorý prvok n0 z domény predpokladáš, že formula (ma(John, n0) ∧ (macka(n0) ∨ pes(n0))) je pravdivá ?”.
- [ ] Make the font in the conversation bubbles smaller – the same as in `sm` inputs, i.e., `0.875rem`. Also, make all controls `sm`.
- [ ] Rename the button from “Vypisať premenné”/“Skryť premenné” to “Zobraziť ohodnotenie premenných”/“Skryť ohodnotenie premenných”

**Comment by crnkjck** [comment]
I’d like the initial statement that the game makes about most formulas to be changed from conditional to plain statement, and to always show the commitment in its own bubble.

I.e., instead of “Ak predpokladáš, že formula (ma(John, n0) ∧ (macka(n0) ∨ pes(n0))) je pravdivá, potom ma(John, n0) je pravdivá”, it should say:

> Predpokladáš, že formula (ma(John, n0) ∧ (macka(n0) ∨ pes(n0))) je pravdivá.
>
> Potom ma(John, n0) je pravdivá.

**Comment by crnkjck** [comment]
@RicsiToth, the changes in messages that I requested required other changes that I kind of expected you would spot and implement. However, it seemed it would take more time to write about them than to fix them, so I did.
Please, have a look at my commit, and check that I didn’t break the logic.

**Comment by RicsiToth** [comment]
@crnkjck I checked your commit and it seems to be fine.

**Pull request merged**
